wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - ${public_port}:80

db:
  image: webhippie/mariadb
  environment:
    MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    MARIADB_ROOT_PASSWORD: ${mysql_root_password}
    MARIADB_INNODB_BUFFER_POOL_SIZE: ${innodb_buffer_pool_size}
